ensime/ensime-emacs

ensime-auto-complete.el, ensime-model.el, ensime-test.el
* Swallow exceptions in the candidate retriever (missing connection won't complain)
* Replace '.' with ' ' if an operator is chosen from candidates.
* Replace 'value_=' with 'value =' for setter completions, and use infix expansion for argument.
* Show type in completion menu for nullary methods.
* Expand '()' for java methods with zero params
* Manually invoke yasnippet expansion when the identifier is already complete (resolves ensime/ensime-server/#753)
* Using emacs function 'read-char-choice' to prompt for choice of paren or block expansion for certain higher order functions.
* Add tests for parameter expansion.
Questions: 
* How usable is the block prompt?
=> Several ergonomics fixes for completion:

ensime-util.el, ensime-vars.el
Remove a couple of calls to `ensime--parent-dir`, which are only hit as a last resort when various parts of the java environment are wrong. Update to `ensime-parent-dir` as defined in `ensime-utils.el` instead.
=> Remove extra dash in ensime--parent-dir

ensime-client.el, ensime-company.el, ensime-inf.el, ensime-mode.el, ensime-test.el
Fix ensime/ensime-server#806.
The earliest time to safely send rpc commands is after receiving the
connection info that includes the protcol version. But it turns out that
most rpc commands don't work until the analyzer is ready so we wait
for that.
=> Fix race condition when server is started but not ready

ensime-company.el
This allows the use of the `tab` key to indent a marked region. Otherwise, we indent the current line.
=> Indent region if mark is active

.travis.yml, README.md, test/.travis.sh, test/dotemacs_test.el
Addresses https://github.com/ensime/ensime-server/issues/448 , although doesn't test ensime-client.el or ensime-startup.el due to issues described in my reply to https://github.com/ensime/ensime-server/issues/448 .
To set this up:
1. Enable ensime/ensime-server on coveralls.io.
2. Merge the pull request.
Travis should test the merged pull request, then it should report to coveralls.io (about 38%). I've included the badge in README.md, so that should work after you set that up.
Hope this helps!
=> Report coverage to coveralls.io using undercover

ensime-client.el, ensime-refactor.el
Note other 'popup' buffers not related to refactoring also suffer from this, but this commit only addresses those for refactoring
=> Fixes ensime/ensime-server#815: close refactoring buffer after close.

ensime-config.el, ensime-startup.el, ensime-util.el, ensime-vars.el, ensime.el
Fix ensime/ensime-server#773.   When an sbt project is detected, run
"sbt gen-ensime" before startup.  Feature is off by default and
controlled by 'ensime-auto-generate-config'
Fix ensime/ensime-server#695
=> Auto-generate .ensime

ensime-completion-util.el, ensime-test.el
This prevents worst-case behavior in forward matching that could (appear to)hang emacs. Resolves ensime/ensime-server#914.
=> Add a regex for matching scala idents in reverse. 

ensime-test.el, test/run_emacs_tests.sh
Also fix a couple Windows problems
Fix ensime/ensime-server#892
I'm pretty happy with the speed improvement as it is, but maybe the next thing we can try is reuse the server between tests, resetting the pres compiler each time.
=> Reuse the index directory in the slow test suite

ensime-client.el, ensime-inf.el, ensime-test.el, ensime-util.el
Two potential issues with this:
* I don't fully understand the .ensime format so what I've done is a guess based on what ensime-sbt generates
* The repl starts up with the following error:
Failed to created JLineReader: java.lang.NoClassDefFoundError: jline/console/completer/Completer
Falling back to SimpleReader.
jline is in SCALA_HOME/lib so I'm not sure how to locate it.  But then since completion doesn't work anyway perhaps this isn't a problem?
=> Get classpath for repl from config rather than server, and remove dependency on scala binary

ensime-startup.el
It might be useful in some cases to be able to configure (or to change) the path to the users ensime directory. E.g. if ".emacs.d" directory is a emacs kit project cloned from github. So, the change will allow to configure the path `(setq user-emacs-ensime-directory ".cache/ensime")` without updating .gitignore.
=> Allows to configure the user's ensime directory

ensime-inf.el, ensime-pkg.el, ensime-stacktrace.el, ensime-test.el
I tested it after pasting stacktrace to buffer that was created by `ensime-stacktrace-switch`. I realize that it's not finished but I would rather like to get some hints about what should I change after someone have a chance to look at code.
This should fix https://github.com/ensime/ensime-server/issues/566 eventually
=> defined stackframes can be folded

ensime-pkg.el, ensime-stacktrace.el
Hideshow is included with emacs but fold-this isn't, so using hideshow makes it easier to install
=> Use hideshow instead of fold-this for foldable stack frames.

ensime-config.el, ensime-inf.el, ensime-test.el
As suggested here: https://github.com/ensime/ensime-server/issues/972#issuecomment-104881777
Implementing this now because it will make it easier to write tests for https://github.com/ensime/ensime-emacs/pull/143
=> Require config file but not server to launch a REPL.

ensime-startup.el, ensime-test.el, test/dotemacs_test.el, test/logback.xml
I can't work out what is causing the transient failures, but this increases the ability to debug any failures in the emacs tests so is useful in its own right.
=> enable server logging during testing

ensime-inspector.el, ensime-macros.el, ensime-ui.el
Emacs 25 will throw a bad bounding indices error if subseq is called on
an empty list with a negative index.
This fixes #233
=> Ensure that cursors are non-negative

ensime-client.el, ensime-config.el, ensime-debug.el, ensime-editor.el, ensime-inspector.el, ensime-macros.el, ensime-notes.el, ensime-search.el, ensime-semantic-highlight.el, ensime-startup.el
The custom `when-let` from `ensime-macros.el` macro is incompatible with `when-let` from `subr-x.el` introduced in Emacs 25, which can cause subtle breakage if a caller expects to get the `subr-x` variant, but ends up with the one from Ensime or vice versa.  See https://github.com/Malabarba/paradox/issues/95 for an example.
This PR replaces the custom macro with `-when-let` from dash.el, which comes at no additional cost since Ensime already depends upon dash.el anyway–I wonder why `when-let` was defined anyway.
Besides, a package should _never_ define unprefixed symbols, so if `when-let` needs to stay for a reason that I'm not aware of, it needs to be renamed (i.e. `ensime-when-let`).
=> Replace custom when-let with dash -when-let

ensime-notes.el
If the error attempting to be printed contains a format string like
`%s`, then printing to the minibuffer will fail with the error "Not
enough arguments for format string".
Example of message that caused me to discover the error:
`Implicit conversion of "syncing %s => %s" using augmentString: (x: String)scala.collection.immutable.StringOps`
Minimal emacs-lisp to reproduce issue:
```emacs-lisp
(message (mapconcat 'identity ["%s"] "\n"))
```
vs
```emacs-lisp
(message "%s" (mapconcat 'identity ["%s"] "\n"))
```
=> Fix format string bug containing `%s`

ensime-client.el, ensime-editor.el, ensime-util.el
The sexp protocol parsing layer has trouble with big files. For example a 1000 line java file might take 1+ seconds to parse. This change falls back on an alternative scheme where the source contents are shared via a temporary file. See ensime/ensime-server#1102
=> Don't send full source file contents over socket.

.drone.yml, Cask, ensime-auto-complete.el, ensime-company.el, ensime-editor.el, ensime-sbt.el, ensime-vars.el, ensime.el, test/dotemacs_test.el, test/run_emacs_tests.sh
This isn't the PR that I really wanted to submit in this area, because I think there is a lot more can be done on separating out the sbt dependency... so I left it as a required (not optional) dependency and raised #253 
The motivation for this PR is that I want to reduce the dependencies to make it easier to bring ENSIME into corporate environments (most notably, **my** corporate environment).
Making `auto-complete` optional is a bit of a hack... it seems that neither `cask` nor emacs package really understand the concept of an optional dependency. So here's the hack:
* remove `auto-complete` from the dependency list
* add it to the `Cask` file as a developer dependency so that it is available for testing (actually we don't have any tests for it, so this is blank)
* remove all `(require …
=> remove hard auto-complete dependency

ensime-startup.el
@rorygraves @hedefalk @yazgoo this is an update to the `build.sbt` file that we use to download ensime-server and its dependencies. Can you please update your variants of this launcher, as the next PR to be merged into master will need the netbeans repo (and I bet you were probably missing some of the finer details anyway, because I forgot to put them in the reference launch script!)
=> ensime-server will soon depend on netbeans jars

ensime-client.el, ensime-editor.el, ensime-util.el
`ensime-config-includes-source-file` is pretty expensive, and was called before every automatic typecheck. For projects with large configs such as ensime itself, I was seeing emacs freeze for 0.5s .
The fix here is to minimize calls to `ensime-config-includes-source-file` by assuming that a file can belong to only one ensime connection. I think that's a pretty reasonable assumption. Let me know if you disagree and I'll think of some other solution.
=> Performance fix when typechecking

ensime-auto-complete.el, ensime-client.el, ensime-company.el, ensime-completion-util.el, ensime-config.el, ensime-mode.el, ensime-semantic-highlight.el, ensime-startup.el
* Add a temporary adaptor function to make param expansion work for
java. Completion is *nice* in java now :-)
* Document (with error) that java home is required in config. This was always the case, but we died with a crap message.
* Don't try to fan out typecheck requests to multiple connections. This
triggers expensive connection-for-sourcefile lookups that choke when
there are *many* source roots.
* Guard our find-file and save-file hooks with ensime-source-file-p. We
were previously taxing *all* buffers with expensive connection
lookups.
* Handle nil semantic highlighting (a hack really).
=> Misc. fixes to make ensime play better with a big, pure java project.

ensime-inf.el
When using ensime with multiple submodules with overlapping
dependencies, I was finding that the exact same jars were being added
multiple times to the classpath. Java doesn't consider this an issue,
but the classpath was long enough due to this issue to exceed the
maximum size allowed for bash on my machine (argument list too long exception).
This is not actually a proper fix for the args list being too long, but should prevent it from happening quite so often.
=> delete duplicate classpath entries

ensime-expand-region.el
That's enough to provide the variable definition.  There's no need to load all of Expand Region.
=> Only require expand region core

ensime-test.el
I want to lock this down for posterity.
=> Require connection-info first in integration suite.

ensime-semantic-highlight.el
Temporary fix for #283. The proper fix will accept SourceFileInfo on the server, so we don't need to require a disk file.
=> Don't attempt to highlight missing files.

ensime-notes.el
Changed the implicit conversion and implicit parameter highlight to be a little less in-your-face: light gray straight underline.
=> Changed the implicit conversion and implicit parameter highlight

ensime-inf.el
This patch changes the regexp for matching scala-compiler and scala-reflect jars in the classpath so that it also matches jars without a version number in their names.
=> Allow scala-compiler version omission in classpath

ensime-semantic-highlight.el, ensime-vars.el
Remove the noisy gutter icon for implicit parameters and conversions.
They're underlined anyway.
=> Fix for #247 - remove the noisy gutter icon for implicits

ensime-startup.el
I noticed this topping the profiler results. My totally unscientific take: it's noticeably snappier now!
=> Disable wasteful display filter functions for server.

ensime-client.el, ensime-mode.el, ensime-refactor.el, ensime-test.el, ensime-vars.el
This is a rudimentary support for most of ensime refactoring functionality using a new `diff-refactor` request.  The current prepare-exec-cancel refactoring method is not affected by the change.
I guess we need to add some commands on top of the standard `diff-mode` like applying all hunks, deleting diff file when all hunks applied, etc... What do you think?
=> Add basic support for diff refactoring

ensime-client.el, ensime-inspector.el, ensime-mode.el, ensime-test.el
File structure server call implementation, available via `imenu` command, replacing scala-mode2 imenu generators. Menu items are formatted with colon instead of parenthesis, so that different backend for imenu is visible.
=> Ensime Imenu: File structure view

README.md
The documentation page starts with resources for learning Emacs. Perhaps it's better to start with installation instructions or basic editor use.
=> Update README.md to point to emacs documentation

ensime-search.el
Also, pedantically change the mode name to include the word `mode`.
=> run hooks in ensime-search-mode-hook [fix #351]

ensime-sbt.el
Fixes #322 
used `completing-read` to fix the error and keep the functionality.
Just wondering now if everything should be using `completing-read`.
Thoughts?
Also, sorry about the whitespace noise -- apparently that was me on this initial commit -- not quite sure what happened there.
=> ensime sbt compilation error

ensime.el
The earlier link pointed to http://github.com/ensime/ensime-server/wiki/Example-Configuration-File
which is now obsolete.
=> Changed the error message to point to troubleshooting guide

ensime-editor.el, ensime-test.el, ensime-util.el
If there is already a statement of `import com.example.MyCoolClass`
and a user is trying to import `com.example.MyOtherCoolClass`,
the result will be `import com.example.{ MyCoolClass, MyOtherCoolClass }`
Prior to this commit, the import statement would have been added
after on a separate line as:
```scala
import com.example.MyCoolClass
import com.example.MyOtherCoolClass
```
Additionally, I thought it might be time to use cask and ecukes for (initially) the non async tasks.  I put those changes in a separate commit in case you weren't too keen on it.
In case it isn't obvious, if you like the new non async integration tests, I am volunteering to convert the rest of them to ecukes tests as well in another PR :bowtie: 
And I can also take a look at the async tests eventually after that.
=> Import qualified name with same base package and group them together

ensime-company.el, ensime-completion-util.el
Candidate fix for #373. This is a pretty aggressive approach where we replace any ident following (point) with the newly completed ident. Whether or not there is a trailing paren.
@fommil I can't decide if this is right, so I'm going to try it at work some. Will you give it a try as well?
=> Delete existing member when completing.

ensime-mode.el, ensime-model.el, ensime-refactor.el, ensime-test.el
Add refactor option to add type annotation to current symbol
Mapped to `C-c C-r a`
Fixes https://github.com/ensime/ensime-emacs/issues/379
Tested with the following examples:
```scala
private val startTime = startDate.toDateTimeAtStartOfDay.getMillis
private val endTime = endDate.toDateTimeAtStartOfDay.getMillis
for {
a <- List(1, 2)
b <- Map(1 -> 1)
(c, d) <- Map("" -> true)
} yield 1
def test = 1
def test2() = 1
def test3(x: Int) = 1
def test4(x: Int = 3) = 1
def test5(x: Int = 3, b: (Int, String) = (1, "")) = 1
def test6(x: Int = 3, b: (Int, String) = (1, ""))(implicit z: (Int, Boolean)) = 1
def sum[A](xs: List[A])(implicit m: List[A] ) = m
def default1(dateStr: String = "a", b: (Int, Int))(implicit x: Int) = { List("") }
def default(
dateStr: String = "a", b: (Int, Int)
)(implicit x: …
```
=> Add refactor option to add type annotation to current symbol

ensime-editor.el, features/scala-insert-import.feature
Inserting an import in a file without a package resulted in a broken
import list. See #393
=> Fix insert import in files without a package

ensime-sbt.el
I've changed `compile` to `test:compile` to make SBT compile the tests as well.  I'm not sure whether that has any unintended side-effects or whether it's even a good idea in general, so I'm opening this PR to "fish for feedback" :sunglasses:
=> Compile tests too

ensime-search.el
Hi,
This pull request fixes two little bugs in the ensime-search module:
1. The RET key works now when emacs is used in a terminal. "RET" and <return> behave differently when used in a terminal or in a GUI. The fallback for <return> is alway "RET", but "RET" does not fallback to <return> which was not mapped and thus ignored.
2. The highlighting did not work correctly, because the function (ensime-make-overlay) was not used correctly.
Hope this helps a bit. Thanks for this fantastic module!
CU
Roll
=> ensime-search: RET key and Highlighting. (#385)

ensime-mode.el, ensime-notes.el, ensime-vars.el
Hi,
I like the icons that show the errors and warnings in the fringe. As I work a lot in terminal mode, it was annoying that these icons did not work, because there is no fringe in terminal mode.
So I made some changes to show the icons in the left margin.
By default, the icons are now shown, but they can be switched of, because the left-margin is also used by git-gutter or linum and they could conflict with these modes. 
What do you think?
Is it worth integrating?
Anyway, I think it should not interfere with the 'normal' window-system mode ;-)
Roll
=> Added gutter icons for compile errors and warnings in terminal mode

ensime-editor.el
When I have a typo and try to import a type at point, emacs freezes and I have to `<C-g>` out.
Local debugging showed that the `suggestions` are a list with `nil` in it (`(nil)`).
So the `when` check doesn't work.
I am an elisp noob, so I am not sure that this is the correct fix. In scala I would not create a `List` or `Seq` with `null` in it, so perhaps this is the underlying problem that actually needs to be addressed?
I'm also unsure how to test this. I'd like to have a feature entry that sets the cursor on a word and then calls the related function. But I'd have to assert that the autocomplete list is not shown (nothing should happens and emacs should not hang), and I don't know how to do that. Happy to hear out any suggestions or pointers.
=> [discussion needed] Fix hanging import type at point when type does not exist

ensime-config.el, ensime-mode.el, ensime-sbt.el
`gen-ensime` produces an SBT error now, so `ensimeConfig` and `ensimeConfigProject` replace previous usage of `gen-ensime` and `gen-ensime-project`.
This fixes #443. I couldn't find a test to update. I'd be happy to add one but I'll need a hand with my rudimentary emacs lisp skills!
=> Replace `sbt gen-ensime` with `sbt ensimeConfig`

ensime-inspector.el, ensime-mode.el
Added option to get name/full-name of type at point
`C-c C-v t` is short name and `C-c C-v T` is full name.
Sending universal argument will add selected type to kill ring
fixes https://github.com/ensime/ensime-emacs/issues/445
=> Added option to get name/full-name of type at point

ensime-inspector.el, ensime-mode.el
Removed duplicated optional in https://github.com/ensime/ensime-emacs/pull/457
Fixes https://github.com/ensime/ensime-emacs/issues/364
- I'd like to know what's the best place to put the function? (currently it's in ensime-mode.el)
- Also is not adding the report content by default to the kill-ring, only if universal argument is provided.
Should be the contrary? added by default to kill-ring and if universal argument is provided just print the content to *messages* buffer?
- Can you try if keymap combination is working?
Have you read all the documentation at [Ensime Emacs](http://ensime.org/editors/emacs/)? Please do, we put a lot of effort into it.
Most problems can be resolved easily by following a simple process, follow through our
[Troubleshooting …
=> Added M-x ensime-troubleshooting

ensime-company.el
Resolves ensime/ensime-emacs#463
=> Use short type names in company-mode templates.

ensime-company.el, ensime-model.el
This changeset includes:
- regex adjustment for by-name parameter recognition
- a completion template adjustment for function arguments with zero parameters (e.g. `() => String`).
The block templates that were generated prior would not include the `()` part which would
cause them to not compile.
=> Support new by-name parameter representation in ensime-server

ensime-company.el
This seems to be a simple oversight - right now the company backend ignores the user's
case sensitivity preference when requesting candidates from the backend.
@aemoncannon - you might want to have a look
=> Respect `ensime-company-case-sensitive` when fetching completions

ensime-mode.el
Add a single autoload cookie.
This should mean that installation instructions could be simplfied to:
(use-package ensime
:config (add-hook 'scala-mode 'ensime-mode))
Or 
(use-package ensime
:ensure t
:config (add-hook 'scala-mode 'ensime-mode))
and use-package will install it also. Perhaps even better, put the `add-hook' form into ensime-mode, then autoload that. Then installation instructions would be "M-x package-install ensime". I can add this also.
=> Add autoload cookie for ensime-mode

ensime-mode.el
Should have added this to last -- apologies.
This should automatically add the scala-mode-hook during package initialisation. This should shrink the installation instructions to a minimum.
=> Add hook into scala mode

ensime-company.el
Fixes #486.
The call to read-char-choice to prompt for { or ( causes point to be moved back to the last position the user typed a character rather than after the text that auto-completion just wrote to the buffer. The result is that method parameters get insert inside the auto-completed method name.
=> Wrap read-char-choice in save-excursion

ensime-test.el
This should make it so ensime-server 2.0-graph won't crash on emacs tests. At least this works for me locally.
=> -XX:MaxDirectMemory size for 2.0-graph build support

ensime-editor.el
`ensime-edit-definition-other-frame` opened definition of symbol in other window instead of opening in other frame. Adding another predicate related to frame fix the issue.
=> Fix ensime-edit-definition-other-frame not working

ensime-startup.el
When showing Startup notification we should display beginning rather than end of the buffer. The same holds for Welcome message.
=> Move point at beginning of a Startup notification

ensime-search.el, ensime-test.el
Remove any text properties (these are preserved for yanked text) before submitting a search query to the server.
The fix for the issue was trivial. The real effort was making the unit test run. There was an existing "Interactive search test" in ensime-test.el that was commented out; probably because it crashed. That problem turned out to be caused by ``split-window`` failing because the search window was too small to be split into the results/entry areas. The tests run in emacs --batch mode which provides a very small frame (about 10x10) which is too small to contain all the windows.
We now gracefully reduce the size of the text entry area based on the size of the search window. I expect no one will ever run into this outside of the unit tests.
Fixes #482
=> Remove text properties from search input

ensime-inf.el, ensime-test.el
When using `ensime-inf-eval-region` to evaluate a Scala expression with multiple blank lines, the interpreter produces the following error:
````
scala>      |      | You typed two blank lines.  Starting a new command.
scala> <console>:1: error: eof expected but '}' found.
}
`````
The fix is to remove all blank lines from the region before sending it to `ensime-inf-eval-region`.
=> flush blank lines when sending region to Scala interpreter

ensime-goto-testfile.el
Steps to reproduce:
1. Open RichPresentationCompilerSpec.scala.
2. Place the cursor on any string inside RichPresentationCompilerSpec.
3. M-x ensime-sbt-do-test-only-dwim.
It runs RichPresentationCompilerThatNeedsJavaLibsSpec instead.
The problem is in incorrect behavior of backward-up-list when the cursor is inside a string. The workaround is ensuring that backward-up-list is not called from a string.
"inside-string?" predicate was taken from here: http://ergoemacs.org/emacs/elisp_determine_cursor_inside_string_or_comment.html
=> Fix sbt-do-test-only when the cursor is inside a string

ensime-inspector.el, ensime-notes.el, ensime-test.el
ensime-type-at-point, ensime-type-at-point-full-name and
ensime-print-errors-at-point with "C-u C-u" prefix argument display
the result inline using the CIDER style overlay.
=> option to display type and errors at point inline

ensime-mode.el
major-mode functions does not take any arguments.
=> Remove needless argument

ensime-auto-complete.el, ensime-client.el, ensime-comint-utils.el, ensime-company.el, ensime-goto-testfile.el, ensime-mode.el, ensime-popup.el, ensime-startup.el, ensime-ui.el, ensime.el, features/step-definitions/ensime-emacs-steps.el, test/ensime-emacs-test.el
I was getting some "missing symbol `find`" errors depending on the order of loading files after starting emacs.
=> cl cleanup

ensime-sbt.el
Play does not follow the SBT standard dir layout, it is sweet to support that though it is configurable to re-layout
=> Support Play's default dir layout

ensime-client.el, ensime-editor.el, ensime-mode.el, ensime-sbt.el, ensime-test.el
- Add ensime-sbt-do-scalariform-only functions
- Refactor common code with ensime-sbt-do-compile-only
=> Use ensimeScalariformOnly to format buffer

ensime-sbt.el
Reverts ensime/ensime-emacs#528
which is reverting the revert. I can reproduce locally according to https://github.com/ensime/ensime-emacs/issues/526 (but I need to open a .scala file in between).
I don't really consider this issue closed properly, this feels like a workaround... it would be much better to work out why it is happening. @greenrd
=> Revert "Revert "Set ensime-inf-overlay-marker in sbt buffers""

ensime-inf.el, ensime-sbt.el
This ensures it will only be set to nil if not already set.
Fixes #526 in the correct way.
=> Create ensime-inf-overlay-marker variable correctly

ensime-sbt.el, ensime-test.el
Simple but not so elegant fix to make `ensimeCompileOnly` and `ensimeScalariformOnly` work with files in test folders
Close #539
=> Make sbt tasks work with test files

ensime-test.el
I've not been able to trace problems with `2.0-graph` emacs tests all the way to the real cause, but this seems to fix it for me locally. Probably has something to do with orient not closing in time.
=> bump timeout before cleanup to 3 seconds

ensime-test.el
To run some tests with `2.0-graph` branch of ENSIME we need to be able to access classfile info.
=> compile projects in find usages & refactor-rename tests

ensime-config.el
Hello,
generating the ensime config file via the `ensime-refresh-config` (from lisp, not interactively) didn't work for me. It created the config file in the wrong folder (not in the project directory but one above). I then found that the `default-directory` used for the sbt process didn't end in a slash, and changing that fixed my problem. But it works when calling it interactively from within a scala buffer that is connected to ensime (i.e. there is a sbt project for this scala buffer and ensime is connected). I don't know why that is…. I didn't investigate further, because I thought it would be better to always wrap the dirname in `file-name-as-directory` when setting it to `default-directory`?
=> ensure default-directory ends with slash

ensime-client.el, ensime-company.el, ensime-config.el, ensime-doc.el, ensime-goto-testfile.el, ensime-macros.el, ensime-mode.el, ensime-notes.el, ensime-sbt.el, ensime-search.el, ensime-util.el, ensime.el
It turns out that almost any operation in indirect buffers caused ensime to crash. This PR is fixing it, so now it is possible to do any operation in indirect buffer as if it was regular buffer.
=> M-. in indirect buffer kills Ensime (#542)

ensime-config.el
it doesn't exists.
This is fix for the case when sources in
.ensime_cache/dep-src/source-jars weren't navigable due to cache
ensime--cache-source-root-set not including
.ensime_cache/dep-src/source-jars since it doesn't existed when the
project were created.
=> Put .ensime_cache/dep-src/source-jars directory into cache even when

ensime-inf.el
if no region is active send current line to Scala interpreter.
=> ensime-inf-eval-region - send current line to Scala interpreter

ensime-mode.el, ensime-sbt.el
- Bind to `C-c C-b C-j` to ENSIME minor mode
=> Add ensime-sbt-send-eol command

ensime-editor.el, ensime-ivy.el
Fixes use of `ensime-use-helm` pointed out by @bomgar
=> Ivy completion for import type at point

ensime-sbt.el
Suggest that the dwim test commands can be run in a test source
file to avoid getting prompted for inputs.
Here's an example of one of the messages when a dwim command is
not run from a test source file:
"Run ‘C-c C-b o’ from a test file to avoid the prompts"
=> Provide hint message for dwim commands

ensime-mode.el, ensime-sbt.el
Broken when dwim was added in 6d83487
Add back `ensime-sbt-do-test` and bind to `C-c C-b T`.  This is
consistent with the documentation:
http://ensime.org/editors/emacs/cheat_sheet/
I'll update the cheat sheet to be consistent with the latest in ensime/ensime.github.io#227
=> Fix test commands in SBT menu

ensime-eldoc.el
`ensime-implicit-notes-at` returns propertized messages (in a list) but the properties were dropped because we were passing the list to `"%s"` of `format`.  `mapconcat`ing the list will preserve the properties.  We should do the same for `ensime-errors-at`, which also returns messages in a list.
I think it is also nice to have it propertized.  Note that the local name of a symbol may be missing, which results in printing `nil: SomeType` in the original code.  We simply ignore symbols without a local name in this PR.
=> Propertize eldoc messages.

ensime-startup.el, ensime-test.el, ensime-vars.el, test/example/build.sbt, test/example/project/plugins.sbt
this PR fix #613.
Also it update server and sbt plugin versions at example project, at least for get `:ensime-server-version` at generated .ensime file.
=> Checks for Milestones, RC server dev. versions at startup  

ensime-startup.el
it fix bug added by #615
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
string-match("-M" nil nil)
s-contains\?("-M" nil)
(lambda (s) (s-contains\? s version))("-M")
mapcar((lambda (s) (s-contains\? s version)) ("-M" "-RC" "SNAPSHOT"))
-map((lambda (s) (s-contains\? s version)) ("-M" "-RC" "SNAPSHOT"))
(-contains\? (-map (function (lambda (s) (s-contains\? s version))) (quote ("-M" "-RC" "SNAPSHOT"))) t)
ensime-dev-version-p(nil)
(if (ensime-dev-version-p ensime-server-version) nil (error (concat "\n\n" "Your build tool has downloaded the stable version of ENSIME " "but you are using the Developer Emacs install.\n\n" "Check that you followed all the steps at http://ensime.org/editors/emacs/install " "including additional steps that are required by your build …
```
=> fix for outdated build tool startup notification error 

ensime-refactor.el, ensime-startup.el
Delete the import duplicate lines.
=> Delete duplicate import lines, when organize java imports.

ensime-popup.el
this is fixing #638 
this was the only usage of `ensime-popup-buffer-p` and as it is directly related about popup I've just copied function from deleted file.
=> fix ensime-show-uses-of-symbol-at-point (#638)

ensime-search.el
Just a tiny correction of an error message when ivy is not installed but used as search interface.
=> Fixed minor copy/paste bug in error message.

ensime-client.el, ensime-editor.el, ensime-helm.el, ensime-model.el
Not particularly pretty but it works.
I tried to write a feature file for the formatter but ecukes complains about a missing method.
`Symbol’s value as variable is void: imenu-auto-rescan`
=> classic show uses and type hierarchy

ensime-editor.el, ensime-search.el
Shows ensime search results in a grep buffer.
If this works good I would use the universal argument for ensime-search to trigger this.
Alternatively we could replace the classic-search with this. Users would lose interactive search though.
=> [feat] add ensime static search
