ensime/ensime-emacs

- ensime-auto-complete.el
It appears that recovering the comment regions in the compiler would require some work, so use a client-side hack to avoid ever making the request.
> Don't complete in comments. See ensime/ensime-server#772

- ensime-auto-complete.el
Include 'doc-face' as a comment face + a refactor in light of an existing helper.
> Fix recognition of comments.

- ensime-test.el
Convert java debugging test to a scala debugging test and make it pass.
> Fix last 'non working' integration test.

- ensime-pkg.el
- test/dotemacs_test.el
Actually this isn't quite doing what it purports to do yet. Stay tuned.
> Ensure we use correct dependency versions in integration tests.

- ensime-config.el
- ensime-editor.el
- ensime-goto-testfile.el
- ensime-test.el
- ensime-util.el
- test/dotemacs_test.el
- test/run_emacs_tests.sh
I feel like this name better describes what the function is actually doing.
> Rename ensime-dir-contains-file-p to ensime-path-includes-dir-p. Add tests.

- ensime-client.el
- ensime-mode.el
Resolves ensime/ensime-server#505
> Add cleanup hooks.

- ensime-test.el
Not sure if travis has JAVA_HOME set, we'll see.
> Fix test suite

- .travis.yml
- README.md
- ensime-client.el
- ensime-test.el
- test/run_emacs_tests.sh
https://github.com/ensime/ensime-server/pull/829
> use JDK_HOME if available

- ensime-client.el
- ensime-doc.el
- ensime-inspector.el
See corresponding PR in ensime-server. Inspector doc links are now very accurate : )
> Use doc server for inspector links.

- ensime-inspector.el
Ready to go when the tests pass.
TODO items to follow in future PRs: to fix source lookups for method overload and packages, then fix doc lookups for packages. These may require some api enrichment.
> Browse docs and sources in inspector, using hotkeys rather than links.

- ensime-startup.el
- use `display-buffer`
- don't filter the sbt output unless started from the test script
- keep the \*ensime-update\* buffer around after success
> Fix ensime/ensime-server#861

- ensime-test.el
- test/run_emacs_tests.sh
these might not go green, because it requires a server feature
> Tests no jre

- ensime-startup.el
close https://github.com/ensime/ensime-server/issues/897
> use project's scala version

- ensime-client.el
- ensime-inspector.el
- ensime-model.el
Blocked on corresponding server PR.
> Use new RPCs to make inspector more accurate.

- shippable.yml
- test/dotemacs_test.el
According to sviridov/undercover.el#7, ensime/ensime-emacs#119.
> PR for test purposes. Ignore it.

- ensime-test.el
This is something we talked about a few weeks ago. Right now I don't think there are any race conditions, but these changes will prevent them from happening in new tests.
> Fix potential race conditions in tests

- ensime-startup.el
note this allows typelevel scala to be used in the user's projects
> use correct version of scala in scalap and scalac

- ensime-goto-testfile.el
this is trivial, just moving some stuff from my personal config to here so that all can share.
> add some more test templates

- test/dotemacs_test.el
assigned to @sviridov for review as per https://github.com/sviridov/undercover.el/issues/6
> use new undercover settings

- ensime-startup.el
Fixes https://github.com/ensime/ensime-server/issues/999
> Fix #999: remove (swank:init-project) from the client

- ensime-test.el
- ensime-vars.el
Added the face support for corresponding PR in `ensime-server`.
> Added faces for deprecated symbols

- ensime-goto-testfile.el
Integration tests in `src/it`
Functional tests in `src/fun`
Part of #183
> Find test file in other source sets

- ensime-inf.el
- ensime-test.el
Fix #190 . Made tests more verbose, it may help diagnose future problems.
> Fix debugger unit test

- .drone.yml
- .gitignore
- Cask
- ensime-config.el
- ensime-editor.el
- ensime-http.el
- ensime-mode.el
- ensime-pkg.el
- ensime-test.el
- ensime.el
and this has the keybindings for the new server features. I'll wait until the server support is merged before updating the wiki.
> preemptive support for new server features

- ensime-client.el
- ensime-startup.el
- ensime-test.el
- test/dotemacs_test.el
- test/logback.xml
~~Do not merge, I just want to run the CI suite.~~
Increase the verbosity of the test suite and make sure that the server replies to all requests.
> During test suite, show server messages on stdout

- ensime-client.el
- ensime-test.el
(from discussions on the emacs mailing list)
> even better fix for the SWANK encoding

- ensime-startup.el
yeah, stop laughing at the back.
> scala-2.9 startup close #152

- ensime-client.el
- ensime-semantic-highlight.el
- ensime-startup.el
- ensime-vars.el
This is probably the first of many necessary fixes.
> Fixes to get elisp CI back up and running.

- ensime-client.el
- ensime-editor.el
- ensime-mode.el
- ensime-startup.el
- ensime-test.el
* In particular, verify that things work in an unsaved file.
* Revise naming of typecheck rpc functions for clarity.
* Get rid of some now unecessary connection-finding optimizations.
* Fix a bug in ensime-owning-connection-for-rootdir
* Changes to make tests run interactively on OSX
> Test of new source file experience.

- ensime-test.el
This reverts commit e4794dd29846205ffd214b43b6e1b62520508149.
> Revert "back out test for unsaved in-memory files"

- ensime-test.el
Misc fixes to broken elisp test of unsaved files.
> Oops. Undefined var.

- ensime-inf.el
Add support for running scala as an inferior process with an assembly file
> search for a scala-compiler jar in :scala-compiler-jars 

- ensime-startup.el
> use the new scala-less assembly jars

- ensime-inf.el
- ensime-test.el
- ensime-util.el
No need for ensime--scan-classpath, replace with -filter.
close #329
> fix REPL launching bug

- ensime.el
This time I've finally actually tested this code path!
> Fix auto-generate code path in my previous commit

- ensime-inspector.el
- ensime-mode.el
- ensime-startup.el
- ensime.el
@aemoncannon are you ok if I rename `ensime-print-type-at-point`? and also this closes #346 
@greenrd can you have a look where I remove the global variable? I think that's right, but I'm no elisp expert.
addresses one use of #332
> Small fixes

- ensime-auto-complete.el
- ensime-company.el
- ensime-completion-util.el
- ensime-inspector.el
- ensime-model.el
- ensime-test.el
This client should be (mostly) backward-compatible with protocol 0.8.19.
> Migrate to protocol 0.8.20 (no type ids!)

- ensime-config.el
> Auto-regenerate .ensime for Build.scala

- ensime-editor.el
close #358 
@aemoncannon @greenrd whoever is around. This is a tiny one.
> return types for ensime-edit-definition

- ensime-startup.el
close #376 
honestly this is a bit hacky, but I keep justifying hacks like this to myself because we'll eventually move to SWANKY over WebSockets.
Yeah, one day.
> keep trying when there is a process and a port

- ensime-debug.el
It's necessary to set breakpoints _before_ attaching; neither setting breakpoints nor
running the program is required after attaching.
Also factor some common code out of ensime-db-start and ensime-db-attach.
> Correct message when using ensime-db-attach

- ensime-inspector.el
Thank you for contributing to ENSIME!
If this is your first time submitting a PR, this is what you can expect:
1. You'll have to agree to the licences we use. You'll get a link to follow in a moment.
2. Your code will be automatically tested. That can take as long as an hour before the results come back. You can read `.drone.yml` to see what is being run.
3. We'll try to review your code and give feedback quickly.
4. Please squash your commits into independent units. We use the commit log as our changelog so it is good if your commit messages are clear and concise.
5. You can request an ENSIME sticker from `@fommil`, be sure to ask if you want one!
6. If everything goes silent, please ping us.
Now, delete this line and everything above it, then tell us which tickets this PR closes (please …
> Fix eldoc-error: wrong number of argument.

- ensime-client.el
- ensime-debug.el
- ensime-mode.el
- ensime-test.el
- test/dotemacs_test.el
- test/run_emacs_tests.sh
https://github.com/ensime/ensime-server/pull/1359 with some test fixes
> fix the integration tests

- ensime-debug.el
- ensime-test.el
attempt to understand and fix #399
> try to reproduce blinking test with debugging enabled

- ensime-editor.el
- features/scala-insert-import.feature
> Skip multiline imports before inserting new import

- ensime-mode.el
> Setup imenu for scala-mode only

- ensime-startup.el
- test/ensime-emacs-test.el
> support typelevel scala releases

- ensime-company.el
I changed the local key binding of the "TAB" key, because it didn't work in terminal mode.
> Changed TAB keybinding to work in terminal mode

- ensime-editor.el
- ensime-helm.el
- ensime-vars.el
Hi.
i want to integrate helm for some ensime features. To test if it works i use helm for import-type-at-point. I'm not sure if I should continue working on it. Is this something worth pursuing?
> Use helm for import-type-at-point

- ensime-client.el
- ensime-completion-util.el
- ensime-model.el
- test/ensime-emacs-test.el
I found a strand of code in here that looks like it needs to be unravelled and removed, but this is the quick fix.
> quick fix for broken unit tests

- ensime-model.el
- test/ensime-emacs-test.el
sorry, forgot to raise this last night before I went to bed.
> massive hack to handle more scala names

- ensime-test.el
breaks the build, temporarily, until https://github.com/ensime/ensime-server/pull/1466 is merged.
> change assertions

- ensime-client.el
- ensime-helm.el
- ensime-search.el
Provides an alternative to ensime-search (optional)
> Use helm to list search results

- ensime-auto-complete.el
- ensime-client.el
- ensime-company.el
- ensime-completion-util.el
- ensime-doc.el
- ensime-macros.el
- ensime-model.el
- test/dotemacs_test.el
- test/ensime-emacs-test.el
> remove client side name parsing

- .drone.yml
- ensime-client.el
- ensime-editor.el
- ensime-inf.el
- ensime-startup.el
- ensime-test.el
- ensime-vars.el
- ensime.el
- test/run_emacs_tests.sh
removing checks for old protocol versions that are no longer supported and making the tests handle new environment variables.
> preparation for ensime-server 1.0

- ensime-auto-complete.el
- ensime-company.el
- ensime-completion-util.el
- ensime-model.el
could potentially close #458
we don't really need to query the payload for this derivable value.
> no reason to ask for 'is-callable

- ensime-vars.el
> Fix typo in ensime-goto-test-configs reference

- Cask
- features/helm-search.feature
- features/step-definitions/ensime-emacs-steps.el
- features/support/env.el
I started working on tests for the helm feature.
> Add test for helm search result format

- ensime-mode.el
- ensime-sbt.el
- ensime-test.el
Resolves: ensime/ensime-emacs#423
Please let me know if changes are needed.
> ensimeCompileOnly support

- ensime-config.el
- ensime-goto-testfile.el
- ensime-inf.el
- ensime-inspector.el
- ensime-mode.el
- ensime-startup.el
- ensime-test.el
- ensime-vars.el
- ensime.el
- test/ensime-emacs-test.el
- use 1.0.0 of the server
- close #446 
- clean up the modeline
- close #467
- close #456
- close #470
> Server 1.0

- ensime-inf.el
- ensime-startup.el
- ensime-test.el
- test/ensime-emacs-test.el
> emacs naming conventions for startup variables

- ensime-startup.el
> if the classfile doesn't exist, it needs updating

- ensime-test.el
Let's try this one more time :)
> fix bad append behaviour

- ensime-startup.el
- ensime.el
- test/dotemacs_test.el
> popup notification on `M-x ensime`

- ensime-compat.el
- ensime-inf.el
- ensime-overlay.el
- ensime-test.el
> evaluate in REPL and display inline like CIDER

- ensime-startup.el
could speed things up dramatically
> hacky enabling of coursier for the install

- .drone.yml
- ensime-startup.el
I forget that coursier needs some envvars to handle snapshots
> coursier for snapshots

- ensime-startup.el
as discussed in https://github.com/ensime/ensime-emacs/pull/516
> update SNAPSHOT info

- ensime-sbt.el
Reverts ensime/ensime-emacs#527
> Revert "Set ensime-inf-overlay-marker in sbt buffers"

- ensime-config.el
hoping to bypass https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24358#77
> simplify the .ensime loading (slightly faster)

- ensime-config.el
- ensime-sbt.el
close #530 and introduce breaking changes for @yyadavalli  (sorry!)
@jmpage if you're around, do you mind doing a review please?
> make the submodule lookup more general, and Windows compatible

- ensime-editor.el
- ensime-mode.el
Based on the comments in https://github.com/ensime/ensime-server/pull/1619 adding the older keybinding and function back for a easier transition path to #531 
Resolve #531
> Add keybindings and older function for easier transition

- ensime-startup.el
> use same version of sbt and coursier as sbt-ensime

- ensime-startup.el
Add SBT instructions for easier transition
> Add SBT instructions when using new .ensime format

- ensime-startup.el
The welcome message is shown every time ensime is started till the use acknowledges it.
Close #565
> Fix welcome message

- ensime-editor.el
- ensime-test.el
Jumps to the type of the thing at point.
Implements https://github.com/ensime/ensime-emacs/issues/554
> edit-definition-of-type-of-thing-at-point

- ensime-editor.el
- features/scala-insert-import.feature
- features/step-definitions/ensime-emacs-steps.el
Should fix https://github.com/ensime/ensime-emacs/issues/523
The importing code is really hard to get right. Isn't this something the server could do?
> Fixed inserting in import groups at point-min

- ensime-company.el
instead of hardcoded values, we use values from customize
refs 579
Thank you for contributing to ENSIME!
If this is your first time submitting a PR, this is what you can expect:
1. You'll have to agree to the licences we use. You'll get a link to follow in a moment.
2. Your code will be automatically tested. That can take as long as an hour before the results come back. You can read `.drone.yml` to see what is being run.
3. We'll try to review your code and give feedback quickly.
4. Please squash your commits into independent units. We use the commit log as our changelog so it is good if your commit messages are clear and concise.
5. You can request an ENSIME sticker from `@fommil`, be sure to ask if you want one!
6. If everything goes silent, please ping us.
Now, delete this line and …
> making more company variables customizable

- ensime-mode.el
- ensime-refactor.el
> Add support for the expand match cases refactoring

- ensime-test.el
I have no real hopes of this fixing the tests, but here goes...
> bump heap for the graph

- ensime-editor.el
Another attempt at fixing #581.
This improves on #596 by handling the case with multiple package statements:
```scala
package foo
package bar
// Import goes here
package object baz
```
> Better import statement injection logic

- ensime-sbt.el
Add colons, and provide better message prompts.
> Improve prompt in ensime-sbt-test-dwim

- Cask
- ensime-helm.el
- ensime-ivy.el
- ensime-search.el
- ensime-vars.el
Related to #186 
Basic support for now (goto source only).
Suggestions on more options to add are welcome.
> Ivy integration for ensime search

- ensime-editor.el
> Show message when ensime-import-type-at-point yields no suggestions

- ensime-startup.el
- Convert `defvar` to `defcustom` for:
- `ensime-startup-notification`
- `ensime-startup-snapshot-notification`
> Customize startup notifications

- ensime-client.el
- `ensime-log-events`
- `ensime-outline-mode-in-events-buffer`
> Convert defvar to defcustom

- ensime-client.el
- ensime-editor.el
- ensime-mode.el
- ensime-notes.el
- ensime-test.el
in prep for https://github.com/ensime/ensime-server/pull/1786
> remove the typecheck-all command (use source mode)

- ensime-client.el
- ensime-editor.el
- ensime.el
depends on https://github.com/ensime/ensime-server/pull/1794
> use the new API call to restart the PC

- ensime-mode.el
Solves #641 
I've just copied the old required methods to this file. looks like functions defined in `inspector.el` was also used for imenu support.
> fix imenu support #641

- ensime-client.el
- ensime-editor.el
- ensime-helm.el
It actually does something. (Helm only)
The code is not final yet. I create this pull request so anyone else working on it can see what i've done so far.
> Find uses of symbol at point

- ensime-mode.el
With this change the the ecukes test run without an error. I don't know if this is just a problem on my machine. 
What happend to the CI build?
> [fix][test] fix ecukes tests

- ensime-editor.el
* Fix wrong ivy-read function call
> Fixup Ivy support for show uses (#655)
